### ISSUE TITLE
Error while loading shared libraries: liblcm.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Merwanski** [CogChameleon/ChromaTag#2]
Hi 

I am getting the following error when I try to run one of the examples 

bash Run_ChromaTag.sh 
../build/bin/Run_ChromaTag_Detector: error while loading shared libraries: liblcm.so.1: cannot open shared object file: No such file or directory

any idea how I can solve this issue?
Do you have a python wrapper around your package?

Thank you
Merwan

**Comment by Merwanski** [comment]
Solved this by 
$ sudo ldconfig -v

check this for more https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s

Merwan

**Comment by donnillionaire** [comment]
> Solved this by
> $ sudo ldconfig -v
> 
> check this for more https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s
> 
> Merwan

this one worked for me!

**Comment by Namyalg** [comment]
I am facing the same issue, when I am trying to deploy a streamlit application on Heroku, any solution for that ?

**Comment by mashli** [comment]
have you solved this problem? how?

**Comment by Merwanski** [comment]
> have you solved this problem? how?

@mashli did you try the solution above with "sudo ldconfig -v"

**Comment by mashli** [comment]
> 

Thank you, Dear Merwanski. I fixed the problem using your method   "sudo ldconfig -v". 
it worked for me!

**Comment by mashli** [comment]
> > have you solved this problem? how?
> 
> @mashli did you try the solution above with "sudo ldconfig -v"

Thank you, Dear Merwanski. I fixed the problem using your method "sudo ldconfig -v".
it did work for me !!!
