### ISSUE TITLE
ubuntu 18.04 -->> error: ‘floor’ was not declared in this scope  / error: ‘sqrt’ was not declared in this scope

### ISSUE THREAD

**Issue by Merwanski** [CogChameleon/ChromaTag#3]
Error while building on Xavier AGX (Ubuntu 18.04)

![image](https://user-images.githubusercontent.com/22295169/57237570-cbfe8000-7027-11e9-8cb5-51085d353d35.png)

**Comment by Merwanski** [comment]
To solve this issue add the following 
#include << cmat.h >> 
in the header of the cpp file, and the errors will disappear 

Merwan

**Comment by oguchiTaka** [comment]
#include <math.h> solved the problem.
